### ISSUE TITLE
Several steps missing in instructions

### ISSUE THREAD

**Issue by momoz** [igiannakas/mmwave-d1mini#4]
I run HomeAssistant OS (HAOS) and have ESPhome installed in HA.  There is no real clear instructions anywhere on how to get the files in what spot to make all of this work.   
I was able to actually hack it together and have it working... (Love it, works excellent).

Couple items to note:  1) I don't think anything references any part of the files in "Components".  May want to remove this to make the whole package cleaner.
2) Before my cobbling together in HAOS(Esphome), I did try on my mac, and got some errors around wrong CPU
3) in HAOS, I had to create a NEW device, adopt it, then edit the YAML file and copy parts of the sensor.yaml over, place the header and packages files in my HAOS (ESPhome directory) config/esphome/headers and config/esphome/packages.
Here is an example of my device (yaml file in ESPhome):  Notice when ESPhome adopted it and created the device, it identified my D1-mini as: esp01_1m.    so I kept this
```

substitutions:
  # change device name to match your desired name
  device_name: garage-occupancy-sensor
  # change sensor name below to the one you want to see in Home Assistant
  device_name_pretty: Garage Occupancy Sensor
  # change the below to be your WiFi SSID
  ssid: SSIDNAME
  # change the below to be your WiFi password
  wifi_password: SSIDPASSWORD
  # UART Pin configured for a D1 Mini stacked setup
  uart_tx_pin: GPIO4
  # TX Pin configured for a D1 Mini stacked setup
  uart_rx_pin: GPIO5
  # RX Pin configured for a D1 Mini stacked setup
  gpio_pin: GPIO16

# include the yml file with the sensor configuration
packages:
  inclusions: !include packages/leapmmw_sensor.yml

esphome:
  name: "garage-sensor"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-E81A78"
    password: "A5ilRQ6U13Ke"

captive_portal:
web_server:
  port: 80
  version: 2
  include_internal: true
```
